<?php
	
	$location = array(	"Johor", 
						"Kedah",
						"Kelantan",
						"Malacca",
					  	"Negeri Sembilan",
					  	"Pahang",
					  	"Penang",
					  	"Perak",
					  	"Perlis",	
					  	"Sabah",
					  	"Sarawak",
					  	"Selangor",
					  	"Terengganu");

	$course = array(	"Accounting",
						"Agricultural Science",
						"Aquaculture",
						"Architecture",
						"Animation",
						"Aerospace",
						"Aircraft Maintenance",
						"Automotive Engineering",
						"Anthropology",
						"Actuarial Science",
						"Advertising",
						"Animal Science",
						"Audiology",
						"ACCA",
						"A-Levels",
						"American Degree Programme",
						"Banking",
						"Biomedical Science",
						"Business Administration",
						"Biomedical Engineering",
						"Biology",
						"Commerce",
						"Computer Engineering",
						"Computer Science",
						"Chemical Engineering",
						"Civil Engineering",
						"Culinary Arts",
						"Communications",
						"Counselling",
						"Chemistry",
						"College Foundations",
						"Canandian Pre-University",
						"Chemical Engineering with Oil and Gas",
						"Construction project management",
						"Design",
						"Dentistry",
						"Drama, Theatre & Film",
						"Economics",
						"Early Childhood Education",
						"Electrical Engineering",
						"Environmental Engineering",
						"Environmental Health",
						"Environmental Science",
						"Events Management",
						"Engineering Technology",
						"Food Technology",
						"Forensic Science",
						"Fashion Design",
						"Food Science",
						"Finance Management",
						"Game Design",
						"Graphic Design",
						"Geology",
						"Human Resource Management",
						"Hospitality Management",
						"History",
						"Interior Design",
						"Information System",
						"Industrial and Manufacturing Engineering",
						"Islamic Finance",
						"Industrial Electronics",
						"ICAEW",
						"Jurisprudence",
						"Journalism Broadcasting",
						"Language Studies",
						"Law",
						"Medical Laboratory Technology",
						"Multimedia",
						"Marketing",
						"Mechanical Engineering",
						"Marine Biology",
						"Marine Engineering",
						"Marine Science",
						"Mathematics",
						"Medicine",
						"Music",
						"Mechatronic Engineering",
						"Nursing",
						"Nutrition and Dietetics",
						"Nanotechnology",
						"Optometry",
						"Physiotherapy",
						"Piloting",
						"Petroleum Engineering",
						"Political Science",
						"Public Relations",
						"Pharmacy",
						"Psychology",
						"Physics",
						"Port Management",
						"Patisserie & Gastronomic Cuisine",
						"Quantity Surveying",
						"Radiography and Medical Imaging",
						"Religious Studies",
						"Sports Science",
						"Sociology",
						"Shipping Management",
						"South Australian Matriculation / SACE International",
						"Traditional Finance",
						"TESOL & TESL",
						"Traditional Medicine",
						"Tourism Management",
						"Urban and Regional Planning",
						"Veterinary Medicine");

	function drawline($color)
	{
			echo "<hr class='$color my-0' style=\"height:3px\"/>";
	}

	function breakLine($times)
	{
		for($i = 0; $i < $times ; $i++)
			echo "</br>";
	}


	
	if($_GET)
		require('collegeDetail.php');
	else								
		require('collegeList.php');

	
?>