<?php
    echo"<footer class='page-footer font-small unique-color-dark'>";
        echo"<div class='container pt-2 mb-0 text-center text-md-left'>";
            echo"<div class='row'>";
                echo"<div class='col-md-3 col-lg-4 col-xl-3 mb-4 mt-3'>";
                    echo"<h6 class='text-uppercase font-weight-bold'>";
                        echo"<strong>GODs</strong>";
                    echo"</h6>";
                    echo"<hr class='deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto' style='width: 60px;'>";
                    echo"<p>Explore top-ranking universities catered to your needs, in one place. Key in details ONCE to apply to multiple institutions.Sift through numerous offers and find the best one for you & your future!</p>";
                echo"</div>";
                echo"<div class='col-md-3 col-lg-2 col-xl-2 mx-auto mb-4 mt-3'>";
                    echo"<h6 class='text-uppercase font-weight-bold'>";
                        echo"<strong>Useful links</strong>";
                    echo"</h6>";
                    echo"<hr class='deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto' style='width: 60px;'>";
                    echo"<p>";
                        echo"<a href='#!'>Your Account</a>";
                    echo"</p>";
                    echo"<p>";
                        echo"<a href='college.php'>Colleges</a>";
                    echo"</p>";
                    echo"<p>";
                        echo"<a href='#!'>Help</a>";
                    echo"</p>";
                echo"</div>";
                echo"<div class='col-md-4 col-lg-3 col-xl-3 mt-3'>";
                    echo"<h6 class='text-uppercase font-weight-bold'>";
                        echo"<strong>Contact</strong>";
                    echo"</h6>";
                    echo"<hr class='deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto' style='width: 60px;'>";
                    echo"<p>";
                        echo"<i class='fa fa-envelope mr-3'></i>";
                        echo"GODs@gmail.com";
                    echo"</p>";
                    echo"<p>";
                        echo"<i class='fa fa-phone mr-3'></i>";
                        echo"+ 01 234 567 88";
                    echo"</p>";
                    echo"<p>";
                        echo"<i class='fa fa-print mr-3'></i>";
                        echo"+ 01 234 567 89";
                    echo"</p>";
                echo"</div>";
            echo"</div>";
        echo"</div>";
        echo"<div class='footer-copyright text-center py-2'>© <?php echo date('Y');?> Copyright:";
            echo"<a href='index.php'> GODs</a>";
        echo"</div>";
    echo"</footer>";
?>
